source("setup.R")
source("functions.R")
source("data_generation.R")
source("models.R")
source("plot_functions.R")

set.seed(100)

## generate synthetic data representing most simple and complex model
## model 1 - simplest:
## prevalence varying by site and month, constant log-odds diff ANC vs community
m1_data<-generate_data_m1()
get_data_plots(m1_data$data_to_model)
## model 5 - most complex:
##prevalence varying by site and month, linear relationship on logit-scale with different slopes and intercepts depending upon gravidity category
m5_data<-generate_data_m5()
get_data_plots(m5_data$data_to_model)
### fit models
m1_fitting<-fit_m1(m1_data$data_to_model,500,1000,1)
m5_fitting<-fit_m5(m5_data$data_to_model,100,200,1)

### check model recaptures parameters 
m1_plots<-get_plots(m1_fitting,m1_data$simulated_survey_data,m1_data$param_df)
m1_plots
m5_plots<-get_plots(m5_fitting,m5_data$simulated_survey_data,m5_data$param_df)
m5_plots
## fit the simplest model to data generated by the most complex to highlight fitting metrics
m1_fit_to_m5_data<-fit_m1(m5_data$data_to_model,100,200,1)

### can see visually a worse fit (NB parameter fit and simulated values should be different)
m1_fit_m5_data_plots<-get_plots(m1_fit_to_m5_data,m5_data$simulated_survey_data,m5_data$param_df)
m1_fit_m5_data_plots$overall_plot

### model 5 has approx 6 more effective params..
m5_fitting$p_d-m1_fit_to_m5_data$p_d

### but still gives better fit adjusting for overfitting via DIC 
m5_fitting$DIC-m1_fit_to_m5_data$DIC

#### USING MODELS TO RECONSTRUCT SURVEY DATA USING ANC
### Generate data with non-normal underlying prevalence by month
### default censors all data apart from a few months every two years
months_to_predict<-generate_data_m1_runif_month()
get_data_plots(months_to_predict$data_to_model)
## fit model with fixed effects by months
predict_months<-predict_months_m1(months_to_predict$data_to_model,100,200,1)

## should now see predictions for months as well as those included in the fitting
predict_months_plot<-get_plots(predict_months,months_to_predict$simulated_survey_data,months_to_predict$param_df,pred_months=months_to_predict$pred_months)
predict_months_plot

### Generate data with non-normal underlying prevalence by site
### default censors sites 15-20
sites_to_predict<-generate_data_m1_runif_site()
## fit model with fixed effects by months
predict_sites<-predict_sites_m1(sites_to_predict$data_to_model,100,200,1)
## should now see predictions for months as well as those included in the fitting
predict_sites_plot<-get_plots(predict_sites,sites_to_predict$simulated_survey_data,sites_to_predict$param_df,pred_sites=sites_to_predict$pred_sites)
predict_sites_plot




complex_fitting$DIC
complex_fitting$p_d

simple_data<-generate_data_simple()


simple_data$data_to_model
simple_data$
simple_fitting<-run_greta_preg_simple(simple_data$data_to_model,100,200,1)
complex_fitting<-run_greta_preg_complex(complex_data$data_to_model,100,200,1)
simple_fitting_complex_data<-run_greta_preg_simple(complex_data$data_to_model,100,200,1)

simple_fitting_complex_data_plot<-get_plots(simple_fitting_complex_data,complex_data$simulated_survey_data,complex_data$param_df)





predict_temp_data<-run_greta_predict_month(temporal_data_to_predict$data_to_model,100,200,1)

site_data_to_predict<-generate_data_simple_FE_site()
check<-site_data_to_predict$data_to_model
predict_spatial_data<-run_greta_predict_site(site_data_to_predict$data_to_model,1000,2000,1)
check<-site_data_to_predict$data_to_model
checksite_data_to_predict$pred_sites

check<-site_data_to_predict$data_to_model


mcmc_intervals(predict_spatial_data$draws)

simple_fitting_complex_data_plot
complex_plots
mcmc_intervals(simple_fitting$draws)
complex_plots
plots$temporal_plot
simple_plots$spatial_plot
dim(complex_fitting$fit_array)
mcmc_intervals(complex_fitting$draws)
rbinom(4, size = 1000, prob = c(0.1,0.2,0.3,0.4))
complex_fitting$simulated_survey_data
simple_fitting$
  
  prev_site<-complex_data$data_to_model%>%group_by(site,ANC)%>%
  summarise(prev=sum(positive)/sum(sample_size))%>%
  pivot_wider(names_from = ANC, values_from = prev, names_prefix = "ANC_")

ggplot(prev_site, aes(x = ANC_0, y = ANC_1)) +
  geom_point() +  # Add points
  geom_text(aes(label = site), vjust = -1) +  # Add site labels
  labs(x = "Prevalence when ANC=0", y = "Prevalence when ANC=1", title = "Site-specific Prevalence Comparison") +
  theme_minimal() +  # Use a minimal theme
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") 
simple_data$param_df